### PR TITLE
card-generator: add new (.images) and change font-family to (NEXA)

### PR DESCRIPTION
**Pull request by karthik558**
* Dereased border radius
* Using Nexa-Regular by default (font)
* Inluded new assets (pics/vector)
* Code rebase (a lit bit)

Signed-off-by: K A R T H I K <karthik.lal558@gmail.com>

### CODE REVIEW

**Comment by httpanand** [comment]
The images i added are taken from a similar series of image from Icons8 . The color grade looks similar for that...
And can you mention the issue with this current font?

**Comment by karthik558** [comment]
Yes images are from icon8 

Monalisa-font looks too classy and i don't think it looks good. 

exx

This is nexa !

**Comment by httpanand** [comment]
Oh this font is nice ! But can you remove those images and grab some images from [here](https://icons8.com/icons/authors/3kSkbuAyjUdG/justicon/external-justicon-lineal-color-justicon/external-christmas-day-justicon-lineal-color-justicon) ?
Because i took all the images from there for a similar appearance.

**Comment by karthik558** [comment]
> Oh this font is nice ! But can you remove those images and grab some images from [here](https://icons8.com/icons/authors/3kSkbuAyjUdG/justicon/external-justicon-lineal-color-justicon/external-christmas-day-justicon-lineal-color-justicon) ? Because i took all the images from there for a similar appearance.

i will add new images tmrw

**Pull request closed without merging**
